# Player FG% vs. Team Winning Pct, First Half 2018-19

## Imports and Setup

In [15]:
# Data Handling and Processing
import pandas as pd
from beakerx import *
from beakerx.object import beakerx
from sklearn import preprocessing

# Other
import os
import time
from tqdm import tqdm

from IPython.display import display

## Data Acquisition

### Player Single-Game FG%

First, need to isolate the players with at least 200FGA through the All-Star Break. From there, can use that player list to get the game logs for each player to facilitate the analysis.

#### Step 1: Isolate the players with at least 200FGA through the All-Star Break
[**LeagueDashPlayerStats docs**](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/leaguedashplayerstats.md) | 
[**Parameters docs**](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/library/parameters.md#StatCategory)

In [3]:
step_1_exists = os.path.isfile('players_w_200fga.csv')
print(step_1_exists)

True

In [4]:
# Import the appropriate libraries
from nba_api.stats.endpoints import leaguedashplayerstats
from nba_api.stats.library.parameters import *

In [5]:
# UDF to get the aggregated player stats given a date range
def get_player_stats_df(
    date_from='2018-10-16',
    date_to='2019-02-14',
    team=0,
    opp_team=0,
    measure_type='Base',
    division=DivisionNullable.default,
    vs_division=DivisionNullable.default,
    conference=ConferenceNullable.default,
    vs_conference=ConferenceNullable.default,
    period=0,
    game_segment=GameSegmentNullable.default,
    home_away=LocationNullable.default,
    outcome=OutcomeNullable.default,
    player_position=PlayerPositionAbbreviationNullable.default,
    player_experience=PlayerExperienceNullable.default,
    starter_bench=StarterBenchNullable.default,
    shot_clock_range=ShotClockRangeNullable.default
    ):

    # Convert team name inputs to ID lists, if applicable
    if opp_team != 0:
        opp_team = [team_full_name_to_id(tm) for tm in opp_team]
    if team != 0:
        team = [team_full_name_to_id(tm) for tm in team]
    
    # Get data
    player_stats = leaguedashplayerstats.LeagueDashPlayerStats(
        last_n_games=0,
        season='2018-19',
        measure_type_detailed_defense=measure_type,
        month=0,
        opponent_team_id=opp_team,
        period=period,
        date_from_nullable=date_from,
        date_to_nullable=date_to,
        team_id_nullable=team,
        division_simple_nullable=division,
        vs_division_nullable=vs_division,
        conference_nullable=conference,
        vs_conference_nullable=vs_conference,
        game_segment_nullable=game_segment,
        location_nullable=home_away,
        outcome_nullable=outcome,
        player_position_abbreviation_nullable=player_position,
        player_experience_nullable=player_experience,
        starter_bench_nullable=starter_bench,
        shot_clock_range_nullable=shot_clock_range)
    
    # Convert to DataFrame and return
    header = player_stats.get_dict()['resultSets'][0]['headers']
    data = player_stats.get_dict()['resultSets'][0]['rowSet']
    return pd.DataFrame(data=data, columns=header)

In [6]:
# If data already exists, just read it in
# If not, pull it from the endpoint
if step_1_exists:
    # Read the data
    player_agg_stats_subset = pd.read_csv('players_w_200fga.csv', 
                                          sep='|', 
                                          encoding='utf-8')
    print('Data read')
else:
    # Pull the data
    player_agg_stats = get_player_stats_df(measure_type='Base')
    
    # Isolate the subset of fields and filter out players with fewer than 200 FGA
    col_subset = ['PLAYER_ID', 'PLAYER_NAME', 'TEAM_ID', 'TEAM_ABBREVIATION', 'FGA']
    player_agg_stats_subset = player_agg_stats[player_agg_stats.FGA >= 200].loc[:, col_subset]
    
    # Store as CSV to conserve endpoint calls for next time
    player_agg_stats_subset.to_csv('players_w_200fga.csv', 
                                   sep='|', 
                                   encoding='utf-8',
                                   index=False)
    
    print('Data pulled and saved')

Data read

#### Preview data

In [20]:
#table = TableDisplay(player_agg_stats_subset.head())
#table.setAlignmentProviderForColumn('m3', TableDisplayAlignmentProvider.CENTER_ALIGNMENT)
#table.setRendererForColumn("y10", TableDisplayCellRenderer.getDataBarsRenderer(False))
#table.setRendererForType(ColumnType.Double, TableDisplayCellRenderer.getDataBarsRenderer(True))
#display(table)
player_agg_stats_subset

#### What is total sum of players with at least 200 FGA through the All-Star Break?

In [10]:
len(player_agg_stats_subset)

280

#### What is the distribution of players per team with at least 200 FGA through the All-Star Break?

In [29]:
(player_agg_stats_subset.groupby('TEAM_ABBREVIATION')
                         .count()['PLAYER_ID']
                         .sort_values(ascending=False))

TEAM_ABBREVIATION
CHI    11
BKN    11
CHA    11
NYK    10
LAL    10
DEN    10
DAL    10
MIL    10
MIN    10
ATL    10
IND    10
PHI    10
PHX    10
POR    10
SAC    10
TOR    10
LAC    10
CLE     9
WAS     9
UTA     9
MIA     9
HOU     8
GSW     8
DET     8
NOP     8
OKC     8
BOS     8
SAS     8
MEM     8
ORL     7
Name: PLAYER_ID, dtype: int64

#### Step 2: Using the player list above, get the game logs for each player
[**PlayerGameLog docs**](https://github.com/swar/nba_api/blob/master/docs/nba_api/stats/endpoints/playergamelog.md)

In [76]:
# Check if data already exists
step_2_exists = os.path.isfile('playerFGP_vs_teamWP.csv')
print(step_2_exists)

True

In [31]:
# Import the appropriate libraries
from nba_api.stats.endpoints import playergamelog

In [32]:
# UDF to get a player's game logs given player ID
def get_player_game_logs(player_id):
    
    # Get game logs data
    p = playergamelog.PlayerGameLog(player_id=player_id, 
                                season_all='2018-19', 
                                season_type_all_star='Regular Season',
                                league_id_nullable='00')
    
    # Convert to DataFrame and return
    header = p.get_dict()['resultSets'][0]['headers']
    data = p.get_dict()['resultSets'][0]['rowSet']
    return pd.DataFrame(data=data, columns=header)

In [78]:
# If data already exists, just read it in
# If not, pull it from the endpoint
if step_2_exists:
    # Read the data
    player_game_logs_trim = pd.read_csv('playerFGP_vs_teamWP.csv', 
                                        sep='|', 
                                        encoding='utf-8')
    print('Data read')

else:
    
    # Iterate through the players and store game logs in global DataFrame
    global_player_game_logs = pd.DataFrame()

    for player in tqdm(player_agg_stats_subset.PLAYER_ID):
        player_df = get_player_game_logs(player)
        global_player_game_logs = global_player_game_logs.append(player_df)
        time.sleep(3)
        
    # Enrich with player information
    global_player_game_logs = global_player_game_logs.merge(player_agg_stats_subset, 
                                                            left_on='Player_ID', 
                                                            right_on='PLAYER_ID')
    # Pare down columns
    col_subset = ['SEASON_ID', 
                  'Player_ID', 
                  'PLAYER_NAME', 
                  'Game_ID', 
                  'GAME_DATE', 
                  'MATCHUP', 
                  'WL',
                  'MIN', 
                  'FGM', 
                  'FGA_x', 
                  'FG_PCT', 
                  'FG3M', 
                  'FG3A', 
                  'FG3_PCT', 
                  'FTM',
                  'FTA', 
                  'FT_PCT', 
                  'OREB', 
                  'DREB', 
                  'REB', 
                  'AST', 
                  'STL', 
                  'BLK', 
                  'TOV',
                  'PF', 
                  'PTS', 
                  'PLUS_MINUS',
                 ]
    global_player_game_logs = global_player_game_logs.loc[:, col_subset]  

    # Clean up column names
    new_col_names = {existing: existing.lower() for existing in col_subset}
    global_player_game_logs.rename(new_col_names, axis=1, inplace=True)
    global_player_game_logs.rename({'fga_x': 'fga'}, axis=1, inplace=True)
    
    # Save full dataset for possible later use
    global_player_game_logs.to_csv('player_game_logs_200FGA_preAS_201819_full.csv',
                                   sep='|',
                                   encoding='utf-8',
                                   index=False)    
    
    # Trim down columns even further for this use case
    col_subset = ['season_id', 
                  'player_id', 
                  'player_name', 
                  'game_id', 
                  'game_date',
                  'matchup', 
                  'wl',
                  'fgm', 
                  'fga', 
                  'fg_pct',]
    player_game_logs_trim = global_player_game_logs.loc[:, col_subset]  
    
    # Store as CSV for later use
    player_game_logs_trim.to_csv('playerFGP_vs_teamWP.csv',
                                 sep='|',
                                 encoding='utf-8',
                                 index=False)
    
    print('Data pulled and saved')

Data read

#### Preview Data

In [79]:
player_game_logs_trim.sample(5)

,season_id,player_id,player_name,game_id,game_date,matchup,wl,fgm,fga,fg_pct
5863,22018,203924,Jerami Grant,21800163,"NOV 08, 2018",OKC vs. HOU,W,3,5,0.600
10392,22018,1628384,OG Anunoby,21800580,"JAN 05, 2019",TOR @ MIL,W,1,6,0.167
7326,22018,202689,Kemba Walker,21800727,"JAN 25, 2019",CHA @ MIL,L,3,12,0.250
6463,22018,203903,Jordan Clarkson,21800612,"JAN 09, 2019",CLE @ NOP,L,9,16,0.563
4773,22018,202697,Iman Shumpert,21800161,"NOV 07, 2018",SAC vs. TOR,L,2,4,0.500

#### Number of records

In [80]:
len(player_game_logs_trim)

13977

#### Verify number of players

In [81]:
player_game_logs_trim.player_id.nunique()

280

#### DataFrame info

In [85]:
player_game_logs_trim.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 13977 entries, 0 to 13976
Data columns (total 10 columns):
season_id      13977 non-null int64
player_id      13977 non-null int64
player_name    13977 non-null object
game_id        13977 non-null int64
game_date      13977 non-null object
matchup        13977 non-null object
wl             13977 non-null object
fgm            13977 non-null int64
fga            13977 non-null int64
fg_pct         13977 non-null float64
dtypes: float64(1), int64(5), object(4)
memory usage: 1.1+ MB

In [87]:
player_game_logs_trim.describe()

,season_id,player_id,game_id,fgm,fga,fg_pct
count,13977.0,1.397700e+04,1.397700e+04,13977.000000,13977.000000,13977.000000
mean,22018.0,7.294428e+05,2.180043e+07,4.549331,9.835945,0.449468
std,0.0,6.974446e+05,2.491648e+02,3.109229,5.607900,0.206324
min,22018.0,1.713000e+03,2.180000e+07,0.000000,0.000000,0.000000
25%,22018.0,2.023390e+05,2.180021e+07,2.000000,6.000000,0.333000
50%,22018.0,2.035070e+05,2.180043e+07,4.000000,9.000000,0.455000
75%,22018.0,1.627750e+06,2.180064e+07,6.000000,13.000000,0.571000
max,22018.0,1.629066e+06,2.180087e+07,21.000000,38.000000,1.000000

## Analysis

In [88]:
# Convert WL column to numeric
def wl_to_numeric(val):
    if val is 'W':
        return 1
    else:
        return 0

player_game_logs_trim.loc[:, 'wl_ind'] = player_game_logs_trim.wl.apply(wl_to_numeric)

In [90]:
# Preview data
player_game_logs_trim.sample(5)

,season_id,player_id,player_name,game_id,game_date,matchup,wl,fgm,fga,fg_pct,wl_ind
12342,22018,203933,T.J. Warren,21800275,"NOV 23, 2018",PHX @ MIL,W,8,13,0.615,1
7805,22018,1627739,Kris Dunn,21800830,"FEB 09, 2019",CHI vs. WAS,L,3,6,0.500,0
11459,22018,1626220,Royce O'Neale,21800445,"DEC 17, 2018",UTA @ HOU,L,4,6,0.667,0
4094,22018,1628402,Frank Jackson,21800280,"NOV 24, 2018",NOP @ WAS,L,2,9,0.222,0
1478,22018,1626166,Cameron Payne,21800321,"NOV 30, 2018",CHI @ DET,L,3,9,0.333,0

#### Develop correlation calculation for single player

In [91]:
# Test correlation on single player
filter = player_game_logs_trim.player_name == 'LeBron James'
lebron_logs = player_game_logs_trim[filter]
lebron_logs.head()

,season_id,player_id,player_name,game_id,game_date,matchup,wl,fgm,fga,fg_pct,wl_ind
8384,22018,2544,LeBron James,21800848,"FEB 12, 2019",LAL @ ATL,L,8,20,0.400,0
8385,22018,2544,LeBron James,21800835,"FEB 10, 2019",LAL @ PHI,L,8,16,0.500,0
8386,22018,2544,LeBron James,21800814,"FEB 07, 2019",LAL @ BOS,W,11,21,0.524,1
8387,22018,2544,LeBron James,21800798,"FEB 05, 2019",LAL @ IND,L,7,12,0.583,0
8388,22018,2544,LeBron James,21800769,"JAN 31, 2019",LAL @ LAC,W,9,22,0.409,1

In [158]:
# UDF to normalize comparison column
def norm_and_corr_calc(comp_col, corr_to_col):
    
    # Convert Series to DataFrame
    df = pd.DataFrame(comp_col, columns=[comp_col.name])
    
    # Create x, where x the 'scores' column's values as floats
    x = comp_col.values.reshape(-1, 1).astype(float)

    # Create a minimum and maximum processor object
    min_max_scaler = preprocessing.MinMaxScaler()

    # Create an object to transform the data to fit minmax processor
    x_scaled = min_max_scaler.fit_transform(x)

    # Run the normalizer on the dataframe
    comp_col_df = pd.DataFrame(x_scaled, columns=[comp_col.name + '_norm'])
    
    # Add corr_to_col to comp_col_df
    comp_col_df[corr_to_col.name] = corr_to_col.astype('float64').values
    
    # Return correlation matrix
    return comp_col_df.corr(method='spearman').iloc[0,1]

In [159]:
# FGM
norm_and_corr_calc(lebron_logs.fgm, lebron_logs.wl_ind)

0.215271093487328

In [160]:
# FGA
norm_and_corr_calc(lebron_logs.fga, lebron_logs.wl_ind)

0.14057948374044035

In [161]:
# FG%
norm_and_corr_calc(lebron_logs.fg_pct, lebron_logs.wl_ind)

0.1333536728431039

#### Scale up to all players on single team

In [148]:
# Test substring logic for single value
player_game_logs_trim.matchup.sample(1).values[0][0:3]

'CLE'

In [153]:
# Scale to all values
teams = list(set([val[:3] for val in player_game_logs_trim.matchup.unique()]))

In [156]:
# Test for single team
filter = player_game_logs_trim.matchup.str.startswith('LAL')
lakers_player_games = player_game_logs_trim[filter]
lakers_player_games.sample(10)

,season_id,player_id,player_name,game_id,game_date,matchup,wl,fgm,fga,fg_pct,wl_ind
7447,22018,203484,Kentavious Caldwell-Pope,21800416,"DEC 13, 2018",LAL @ HOU,L,2,7,0.286,0
6556,22018,1628404,Josh Hart,21800035,"OCT 20, 2018",LAL vs. HOU,L,5,13,0.385,0
4828,22018,1627826,Ivica Zubac,21800596,"JAN 07, 2019",LAL @ DAL,W,1,2,0.500,1
8153,22018,202362,Lance Stephenson,21800562,"JAN 02, 2019",LAL vs. OKC,L,1,5,0.200,0
8396,22018,2544,LeBron James,21800401,"DEC 10, 2018",LAL vs. MIA,W,10,19,0.526,1
8434,22018,1628366,Lonzo Ball,21800526,"DEC 28, 2018",LAL vs. LAC,L,7,16,0.438,0
4988,22018,201580,JaVale McGee,21800782,"FEB 02, 2019",LAL @ GSW,L,4,5,0.800,0
6518,22018,1628404,Josh Hart,21800585,"JAN 06, 2019",LAL @ MIN,L,3,12,0.250,0
7930,22018,1628398,Kyle Kuzma,21800835,"FEB 10, 2019",LAL @ PHI,L,14,21,0.667,0
7436,22018,203484,Kentavious Caldwell-Pope,21800574,"JAN 04, 2019",LAL vs. NYK,L,6,16,0.375,0

In [164]:
rows = []
for player in lakers_player_games.player_name.unique():
    
    # Isolate Player
    player_logs = lakers_player_games[lakers_player_games.player_name == player]

    # Calculate correlations
    fga_corr = norm_and_corr_calc(player_logs.fga, player_logs.wl_ind)
    fgm_corr = norm_and_corr_calc(player_logs.fga, player_logs.wl_ind)
    fgp_corr = norm_and_corr_calc(player_logs.fga, player_logs.wl_ind)
    
    # Append values
    rows.append([player, fga_corr, fgm_corr, fgp_corr])
    
lakers_corr_df = pd.DataFrame(rows, columns=['player', 'fga_corr', 'fgm_corr', 'fg_pct_corr'])

In [171]:
lakers_corr_df.dropna().sort_values('fg_pct_corr', ascending=False)

                     player  fga_corr  fgm_corr  fg_pct_corr
7              LeBron James  0.140579  0.140579     0.140579
4  Kentavious Caldwell-Pope  0.077221  0.077221     0.077221
2              JaVale McGee  0.071138  0.071138     0.071138
8                Lonzo Ball  0.020580  0.020580     0.020580
1               Ivica Zubac -0.100279 -0.100279    -0.100279
5                Kyle Kuzma -0.209163 -0.209163    -0.209163
0            Brandon Ingram -0.212332 -0.212332    -0.212332
6          Lance Stephenson -0.258927 -0.258927    -0.258927
3                 Josh Hart -0.324799 -0.324799    -0.324799

#### Scale to all players on all teams

In [177]:
# Empty list to persist rows
rows = []

# Iterate through each team
for team in tqdm(teams):
    
    # Isolate player game logs for team
    filter = player_game_logs_trim.matchup.str.startswith(team)
    tm_df = player_game_logs_trim[filter]
    
    # For each player with game on team
    for player in tm_df.player_name.unique():

        # Isolate Player
        player_logs = tm_df[tm_df.player_name == player]

        # Calculate correlations
        fga_corr = norm_and_corr_calc(player_logs.fga, player_logs.wl_ind)
        fgm_corr = norm_and_corr_calc(player_logs.fga, player_logs.wl_ind)
        fgp_corr = norm_and_corr_calc(player_logs.fga, player_logs.wl_ind)

        # Append values
        rows.append([team, player, fga_corr, fgm_corr, fgp_corr, len(player_logs)])

corr_df = pd.DataFrame(rows, columns=['team', 'player', 'fga_corr', 'fgm_corr', 'fg_pct_corr', 'gp']).dropna()

100%|██████████| 30/30 [00:03<00:00,  8.70it/s]

In [179]:
corr_df[corr_df.gp >= 20].sort_values('fg_pct_corr', ascending=False)

    team                   player  fga_corr  fgm_corr  fg_pct_corr  gp
217  MEM           Justin Holiday  0.418296  0.418296     0.418296  21
112  POR               Seth Curry  0.391724  0.391724     0.391724  51
27   ORL                 Mo Bamba  0.362027  0.362027     0.362027  47
209  CLE         Tristan Thompson  0.356152  0.356152     0.356152  35
195  CHA              Tony Parker  0.341505  0.341505     0.341505  46
113  POR             Zach Collins  0.338574  0.338574     0.338574  57
265  CHI              Robin Lopez  0.326236  0.326236     0.326236  50
107  POR              Jake Layman  0.317478  0.317478     0.317478  46
249  WAS                John Wall  0.311643  0.311643     0.311643  32
251  WAS          Markieff Morris  0.310860  0.310860     0.310860  34
38   PHX              T.J. Warren  0.303041  0.303041     0.303041  43
300  NYK         Tim Hardaway Jr.  0.300762  0.300762     0.300762  46
283  MIA            James Johnson  0.294917  0.294917     0.294917  40
110  POR             Nik Stauskas  0.288474  0.288474     0.288474  44
147  SAC          Nemanja Bjelica  0.280904  0.280904     0.280904  56
262  CHI                Kris Dunn  0.260567  0.260567     0.260567  31
60   ATL            Kevin Huerter  0.259719  0.259719     0.259719  54
51   TOR               OG Anunoby  0.259137  0.259137     0.259137  48
208  CLE              Rodney Hood  0.252178  0.252178     0.252178  45
321  MIL              George Hill  0.251459  0.251459     0.251459  32
18   UTA              Kyle Korver  0.247469  0.247469     0.247469  35
231  BKN  Rondae Hollis-Jefferson  0.231930  0.231930     0.231930  48
201  CLE            Collin Sexton  0.223151  0.223151     0.223151  58
69   SAS        LaMarcus Aldridge  0.222282  0.222282     0.222282  58
130  DAL               J.J. Barea  0.218200  0.218200     0.218200  38
9    LAC         Patrick Beverley  0.207440  0.207440     0.207440  59
219  MEM               Marc Gasol  0.205578  0.205578     0.205578  53
70   SAS          Marco Belinelli  0.196113  0.196113     0.196113  57
90   MIN               Taj Gibson  0.195111  0.195111     0.195111  56
233  BKN        Spencer Dinwiddie  0.193134  0.193134     0.193134  49
..   ...                      ...       ...       ...          ...  ..
89   MIN         Robert Covington -0.210308 -0.210308    -0.210308  22
92   LAL           Brandon Ingram -0.212332 -0.212332    -0.212332  46
169  NOP            Darius Miller -0.212536 -0.212536    -0.212536  54
50   TOR            Norman Powell -0.214325 -0.214325    -0.214325  37
145  SAC           Justin Jackson -0.226301 -0.226301    -0.226301  52
256  CHI         Antonio Blakeney -0.226919 -0.226919    -0.226919  42
317  PHI          Wilson Chandler -0.231887 -0.231887    -0.231887  36
306  PHI                JJ Redick -0.232466 -0.232466    -0.232466  54
172  NOP            Jahlil Okafor -0.233488 -0.233488    -0.233488  38
232  BKN           Shabazz Napier -0.234610 -0.234610    -0.234610  47
223  BKN             Allen Crabbe -0.243234 -0.243234    -0.243234  32
193  CHA            Nicolas Batum -0.243683 -0.243683    -0.243683  57
119  DEN             Monte Morris -0.243733 -0.243733    -0.243733  57
53   TOR              Serge Ibaka -0.245319 -0.245319    -0.245319  55
77   GSW             Kevon Looney -0.245862 -0.245862    -0.245862  57
164  OKC              Paul George -0.246411 -0.246411    -0.246411  56
98   LAL         Lance Stephenson -0.258927 -0.258927    -0.258927  56
218  MEM            Kyle Anderson -0.279554 -0.279554    -0.279554  43
323  MIL          Khris Middleton -0.288821 -0.288821    -0.288821  54
131  DAL            Jalen Brunson -0.290304 -0.290304    -0.290304  49
76   GSW             Kevin Durant -0.305907 -0.305907    -0.305907  57
104  POR              CJ McCollum -0.318005 -0.318005    -0.318005  56
187  CHA              Jeremy Lamb -0.321378 -0.321378    -0.321378  54
95   LAL                Josh Hart -0.324799 -0.324799    -0.324799  54
165  OKC        Russell Westbrook -0.357109 -0.357109    -0.357109  49
105  POR           Damian Lillard -0.424790 -0.424790    -0.424790  56
308  PHI             Jimmy Butler -0.438663 -0.438663    -0.438663  36
236  DET              Bruce Brown -0.442165 -0.442165    -0.442165  49
250  WAS          Kelly Oubre Jr. -0.453382 -0.453382    -0.453382  29
158  IND           Victor Oladipo -0.515288 -0.515288    -0.515288  36

[283 rows x 6 columns]

In [212]:
['ALL TEAMS'] + sorted(teams)

['ALL TEAMS',
 'ATL',
 'BKN',
 'BOS',
 'CHA',
 'CHI',
 'CLE',
 'DAL',
 'DEN',
 'DET',
 'GSW',
 'HOU',
 'IND',
 'LAC',
 'LAL',
 'MEM',
 'MIA',
 'MIL',
 'MIN',
 'NOP',
 'NYK',
 'OKC',
 'ORL',
 'PHI',
 'PHX',
 'POR',
 'SAC',
 'SAS',
 'TOR',
 'UTA',
 'WAS']

In [217]:
!jupyter nbextension enable --py --sys-prefix widgetsnbextension

Enabling notebook extension jupyter-js-widgets/extension...
      - Validating: OK

In [223]:
import ipywidgets as widgets

# Dropdown to select team
team_dropdown = widgets.Dropdown(
                            options=['ALL TEAMS'] + sorted(teams),
                            value='ALL TEAMS',
                            description='Select Team: ',
                            disabled=False,
                        )

# Slider to select minimum number of games played
gp_min_slider = widgets.IntSlider(
                            value=25,
                            min=corr_df.gp.min(),
                            max=corr_df.gp.max(),
                            step=1,
                            description='Min. GP:',
                            disabled=False,
                            continuous_update=False,
                            orientation='horizontal',
                            readout=True,
                            readout_format='d',
                        )
"""
# Button to output DF
output_button = widgets.Button(
                            description='Update Data',
                            disabled=False,
                        )
# Function to be executed on button click
def on_button_clicked(b):
    team_filter = corr_df.team == team_dropdown.value
    min_gp_filter = corr_df.gp >= gp_min_slider.value
    corr_df[(team_filter) & (min_gp_filter)].sort_values('fg_pct_corr', ascending=False)
    
# Set button click action
output_button.on_click(on_button_clicked)
"""

def view(x='',y=25):
    team_filter = corr_df.team == x
    min_gp_filter = corr_df.gp >= y
         
    if x=='ALL TEAMS': return corr_df[min_gp_filter].sort_values('fg_pct_corr', ascending=False).head(15)
    corr_df[(team_filter) & (min_gp_filter)].sort_values('fg_pct_corr', ascending=False)
         
widgets.interactive(view, x=team_dropdown, y=gp_min_slider)

interactive(children=(Dropdown(description='Select Team: ', options=('ALL TEAMS', 'ATL', 'BKN', 'BOS', 'CHA', …

In [216]:
team_filter = corr_df.team == team_dropdown.value
min_gp_filter = corr_df.gp >= gp_min_slider.value
corr_df[(team_filter) & (min_gp_filter)].sort_values('fg_pct_corr', ascending=False)

    team          player  fga_corr  fgm_corr  fg_pct_corr  gp
278  BOS    Terry Rozier  0.190414  0.190414     0.190414  57
276  BOS   Marcus Morris  0.183142  0.183142     0.183142  53
272  BOS  Gordon Hayward  0.167719  0.167719     0.167719  53
273  BOS    Jaylen Brown  0.034200  0.034200     0.034200  53
271  BOS      Al Horford -0.010943 -0.010943    -0.010943  48
274  BOS    Jayson Tatum -0.098106 -0.098106    -0.098106  58
277  BOS    Marcus Smart -0.152868 -0.152868    -0.152868  57
275  BOS    Kyrie Irving -0.198862 -0.198862    -0.198862  47

In [224]:
gp_min_slider.value

25

In [225]:
team_dropdown.value

'CHA'